### ISSUE TITLE
Login page: Footer blocking

### ISSUE THREAD

**Issue by wei-Z** [IME-LLC/TakeOut#5]
Please check below, it seems the footer color will cover the whole content.
This happens when I change to the default login page in the mean folder.
![image](https://cloud.githubusercontent.com/assets/13737993/14583911/77fe7958-03fe-11e6-9142-4ac8860c5e1a.png)

![image](https://cloud.githubusercontent.com/assets/13737993/14583905/53b6ba88-03fe-11e6-912d-10cd659c8581.png)

**Comment by QiyuLi** [comment]
我checkout了你的branch，没有发现这个问题。
这个问题解决了吗？

**Comment by wei-Z** [comment]
@QiyuLi 还没有，如果直接用mean里自带的sign in page还是会有这个问题；如果不加那个margin好像也会出问题。

**Comment by QiyuLi** [comment]
找到问题了。
要按照bootstrap的基本grid system操作，即先有行再有列。
bootstrap requires **row** and **column**
```
<div class="row">
  <div class="col-md-12 text-center">...</div<
</div>
```

在modules\users\client\views\authentication\signin.client.view.html中：
需要在最外面包裹一层 `<div class="row">...</div>`

**Comment by QiyuLi** [comment]
mean官方没有出错的原因是在<div class="content">之中只有一个<div>，可以默认只有1个row
而我们的content中有2个div，一个是内容，一个是footer，如果不写<div class="row">，系统就会把2个div当成一个row，所以重叠显示了。

**Comment by wei-Z** [comment]
谢啦辛苦啦 我再test一下

**Comment by wei-Z** [comment]
Make sense

**Comment by QiyuLi** [comment]
@wei-Z Let me know if you solve the problem.

**Comment by wei-Z** [comment]
@QiyuLi I just tested it, it works like a charm, thanks for your help.

**Comment by QiyuLi** [comment]
@wei-Z please close it.
